# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['pastedrop.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'IPython',
        'Cython',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'black',
        'cryptography',
        'ipykernel',
        'jedi',
        'jinja2',
        'jsonschema',
        'jupyter_client',
        'jupyter_core',
        'lxml',
        'matplotlib',
        'nbformat',
        'nacl',
        'numpy',
        'parso',
        'pkg_resources',
        'prompt_toolkit',
        'pygments',
        'pytest',
        'setuptools',
        'tkinter',
        'traitlets',
        'wcwidth',
        'yapf',
        'zmq',
    ],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PasteDrop',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
